name: Mirror to Ebrains

on: push

jobs:
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      - name: sycnmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "arbor-sim/arbor"
          source_branch: "master"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/arbor-sim/arbor.git"
          destination_branch: "master"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "arbor-sim/arbor"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/arbor-sim/arbor.git"
          destination_branch: "refs/tags/*"

